
trigger:
- master

pool:
  name: Hosted VS2017
  demands: azureps

steps:
- task: AzurePowerShell@3
  displayName: 'Azure PowerShell script: azuredeploy.ps1'
  inputs:
    azureSubscription: 'PAT Production'
    ScriptPath: ps/azuredeploy.ps1
    ScriptArguments: '-dtap development -sourcePath $(Build.Repository.LocalPath) -SourceVersion $(Build.BuildNumber) -WhatIf $true'
    preferredAzurePowerShellVersion: 6.7.0

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\resource-groups'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\resource-groups'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\ps'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\ps'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'